### ISSUE TITLE
Rewrite description formatting 

### ISSUE THREAD

**Issue by MesterMan03** [Openphones/OpenPhones-website#27]
The description of an item might contain new lines (\n)
The client should make sure these are replaced with the HTML equivalent <br>

**Comment by MesterMan03** [comment]
The new lines are nice, but I realised we'll need more formatting for the description.
So with that, descriptions will have a strict and defined style.
To ensure security, process the descriptions are text and only process the following markdown:
[b] [/b] : **Bold text**
[i] [/i] : *Italic text*
[im] [/im] : IMEI (this should have a nice formatting so it actually stands out and when it's clicked, it should redirect to an IMEI checker site)
[eol] [/eol] : End of Life (just like the IMEI, this should have its custom formatting)

***Warning: The client should always treat the description as literal text and only create html tags that are known to be safe***

**Comment by noClaps** [comment]
Can you give an example of what the markdown will look like as the client receives it?

**Comment by MesterMan03** [comment]
[im]472948205030304826[/im]
[eol]2069/04/20[/eol]

[b]Condition[/b]
The phone is in perfect condition, [i]no scratches or damage can be seen.[/i]

[u]iMessage is not available :([/u]
