### ISSUE TITLE
Remove quantity selector from stock items

### ISSUE THREAD

**Issue by MesterMan03** [Openphones/OpenPhones-website#32]
Stock items are not meant to be bought in bulk, so they shouldn't have a quantity selector.
The API is not yet ready to sanitise this yet, but it's WIP.

**Comment by noClaps** [comment]
I can add a maximum limit to that if you can provide the current quantity in stock through the API. That way if we have 3 phones in stock and someone wants 2, they still have the option for it without having to add them one by one.

**Comment by MesterMan03** [comment]
That's not what I meant. Every phone in the stock section is a single device, that's why you can't buy more than 1 per listing.

**Comment by noClaps** [comment]
Ah okay, will do.
