### ISSUE TITLE
Get ready for API change (overrides)

### ISSUE THREAD

**Issue by MesterMan03** [Openphones/OpenPhones-website#33]
# API feature concept: model overrides

Model overrides are basically just fancy names of colours and storage options. They are called overrides, because they override certain aspects of the model.
Starting with the implementing API version, every product will have an extra "overrides" field.
This is an object that has two fields: "color" and "storage".

"color" is an array, every item is an object with the following fields:
1. name : a string of the colour's English name, used for storage compatibility (explained later)
2. color : a string of the hex rgb of the colour, used for the UI (so it can have nice coloured circles corresponding to the correct colour)

"storage" is also an array, its items are structured like this:
1. size : a number of the storage size in GB (gigabyte, not gibibyte!!!), used to tell the server which size the user bought
2. name : a string of a human readable name for the storage option (for example "256 GB")
3. colorcomp : an array of strings that tells you what colours that size option is compatible with. If undefined, it's compatible with all colours
4. price: a number of the new price for the phone (affected by currency settings). If undefined, use default price

An example "overrides" object looks like this:
```javascript
{
    "color": [
        { "name": "black", "color": "#000000" },
        { "name": "red", "color": "#ff0000" }
    ],
    "storage":
        { "size": 128, "name": "128 GB", "colorcomp": ["black"] },
        { "size": 256, "name": "256 GB", "price": 9999.99 }
    ]
}
```

This example means that I could buy a 256 GB model in all 2 colours for 9999.99 in the currency I chose, and a 128 GB model for the default price but only in black.

***Important***: the default overrides for a phone should always be the first elements of the different arrays, so using the previous example, the UI should show a 128 GB black phone by default.

## Data to server

When sending the cart to the server to make a checkout session, each item should also include an extra "overrides" section (it's always mandatory, since phones have default overrides). Inside the "overrides" object, there should be a "color" and "size" field, which should correspond to the overrides' "name" and "size" fields respectively.

Using our example if I wanted to buy a red 256 GB phone, the item should look like this:
```
{ "id": "...", "quantity": ..., "overrides": { "color": "red", "size": 256 } }
```

## Possible problems

If a user buys the same phone with different overrides, it should be treated as different items in the cart.
So if I buy phone A in black and red, my cart should show two items, with their chosen colours.

## FINAL WARNING, DO NOT IGNORE

**Don't merge this feature until the server is ready. Create a new branch for it and use that for the code changes, but do not fully implement it until server can handle it**

**Comment by MesterMan03** [comment]
Server is now supported with this change, waiting for client

**Comment by noClaps** [comment]
On creating a checkout session, I get an error 400. My request body is in the format:

```json
{
  "items": [
    {
      "id": "pixel-6a-black",
      "quantity": 1,
      "overrides": {
        "color": "charcoal",
        "size": 128
      }
    }
  ],
  "type": "stripe"
}
```

Is there a different request format that I should be using?

**Comment by MesterMan03** [comment]
Lol my bad
fixed
